version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    env_file:
      - .env/development/database
      - .env/development/web

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
