version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env/development/web
      - .env/development/database

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
